language: java

sudo: false # faster builds

jdk:
  - openjdk11

dist: trusty
  
script: 

  - mvn clean install
  
  - mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)
